name: inject.example.coffee
description: A simple example of using package:inject

dependencies:
  inject:
    path: ../../package/inject

dev_dependencies:
  build_runner: ^1.0.0
  inject_generator:
    path: ../../package/inject_generator
  test: ^1.0.0
